name: Compile Assets (Vite)
on: [push, pull_request]
jobs:
  build-assets:
    strategy:
      matrix:
        operating-system:
          - ubuntu-22.04
        php-version:
          - '8.3'
    name: ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: curl, dom, gd, libxml, mbstring, zip, mysql, xml, intl, bcmath, redis-phpredis/phpredis@6.0.1
          ini-values: error_reporting=E_ALL
          coverage: pcov
          tools: composer:v2
        env:
          REDIS_CONFIGURE_OPTS: --enable-redis
      - name: Configure Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install Composer Dependencies
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --optimize-autoloader
      - name: Install JS Dependencies
        run: bun install
      - name: Compile Assets (Vite)
        run: bun run build
