name: Compile Assets (Vite)
on: [push, pull_request]
jobs:
  build-assets:
    strategy:
      matrix:
        operating-system:
          - ubuntu-22.04
    name: ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}
    steps:
      - uses: actions/checkout@v1
      - name: Configure Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install Composer Dependencies
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --optimize-autoloader
      - name: Install JS Dependencies
        run: bun install
      - name: Compile Assets (Vite)
        run: bun run build
