name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest, ubuntu-18.04, or ubuntu-16.04
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for submitting your first issue. Please make sure it follows our Issue Template and you have provided all information.'' first issue'
        pr-message: 'Thank you for submitting your first pull request. Please make sure it follows our Contributing Template and you have tested the code you are issuing this pull request on.'' first pr'
